version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: google-oauth-postgres-prod
    environment:
      - POSTGRES_DB=YourApiDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD:-YourStrong@Passw0rd}
    ports:
      - "5455:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - google-oauth-network-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d YourApiDb"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Seq Logging Server
  seq:
    image: datalust/seq:latest
    container_name: google-oauth-seq-prod
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
      - "5342:5341"
    volumes:
      - seq_data_prod:/data
    networks:
      - google-oauth-network-prod
    restart: unless-stopped
    # Production optimizations
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # ASP.NET Core Web API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-oauth-api-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=YourApiDb;Username=postgres;Password=${DB_PASSWORD:-YourStrong@Passw0rd}
      - Google__ClientId=${GOOGLE_CLIENT_ID}
      - Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - Google__RedirectUri=${GOOGLE_REDIRECT_URI}
      - Jwt__SecretKey=${JWT_SECRET_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpirationMinutes=${JWT_EXPIRATION_MINUTES:-60}
    ports:
      - "7002:80"
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
    networks:
      - google-oauth-network-prod
    restart: unless-stopped
    # Production optimizations
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  postgres_data_prod:
    driver: local
  seq_data_prod:
    driver: local

networks:
  google-oauth-network-prod:
    driver: bridge 